export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb786",
        "on-primary": "#002e6a",
        "surface-container-low": "#191b23",
        "on-tertiary-fixed-variant": "#723600",
        "surface-dim": "#10131a",
        "outline-variant": "#424754",
        "surface-bright": "#363941",
        "on-tertiary": "#502400",
        "on-secondary-container": "#00311f",
        "tertiary-container": "#df7412",
        "secondary": "#4edea3",
        "primary": "#adc6ff",
        "tertiary": "#ffb786",
        "surface-container-lowest": "#0b0e15",
        "surface-container-highest": "#32353c",
        "surface-tint": "#adc6ff",
        "primary-fixed-dim": "#adc6ff",
        "error-container": "#93000a",
        "on-secondary-fixed": "#002113",
        "on-primary-fixed": "#001a42",
        "on-primary-fixed-variant": "#004395",
        "primary-container": "#4d8eff",
        "tertiary-fixed": "#ffdcc6",
        "on-secondary": "#003824",
        "on-surface-variant": "#c2c6d6",
        "inverse-primary": "#005ac2",
        "surface": "#10131a",
        "on-surface": "#e1e2ec",
        "on-primary-container": "#00285d",
        "surface-variant": "#32353c",
        "primary-fixed": "#d8e2ff",
        "on-secondary-fixed-variant": "#005236",
        "on-background": "#e1e2ec",
        "on-tertiary-fixed": "#311400",
        "on-tertiary-container": "#461f00",
        "error": "#ffb4ab",
        "secondary-container": "#00a572",
        "surface-container-high": "#272a31",
        "on-error": "#690005",
        "inverse-on-surface": "#2e3038",
        "secondary-fixed": "#6ffbbe",
        "background": "#10131a",
        "inverse-surface": "#e1e2ec",
        "outline": "#8c909f",
        "surface-container": "#1d2027",
        "secondary-fixed-dim": "#4edea3"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "lg": "24px",
        "gutter": "24px",
        "sm": "8px",
        "container-max": "1440px",
        "md": "16px",
        "xl": "40px",
        "xs": "4px",
        "base": "4px"
      },
      "fontFamily": {
        "label-md": ["Geist"],
        "display-lg": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Geist"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"]
      }
    },
  },
  plugins: [],
}
